version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_container
    volumes:
      - database_data:/app/database
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  database_data:
    driver: local
