CREATE TABLE IF NOT EXISTS servers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  active_category_id INTEGER NOT NULL,
  archive_category_id INTEGER NOT NULL,
  role_manager_id INTEGER NOT NULL,
  feed_channel_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  role_team_id INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ctfs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  server_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  text_channel_id INTEGER NOT NULL,
  event_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  msg_id INTEGER NOT NULL,
  ctftime_id INTEGER NOT NULL,
  FOREIGN KEY (server_id) REFERENCES server (id)
);

CREATE TABLE IF NOT EXISTS reports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ctf_id INTEGER NOT NULL,
  place INTEGER NOT NULL,
  solves INTEGER NOT NULL,
  score INTEGER NOT NULL,
  last_update INTEGER NOT NULL,
  FOREIGN KEY (ctf_id) REFERENCES ctfs (id)
);

CREATE TABLE IF NOT EXISTS creds (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT NOT NULL,
 password TEXT NOT NULL,
 personal BOOLEAN NOT NULL,
 ctf_id INTEGER NOT NULL,
 FOREIGN KEY (ctf_id) REFERENCES ctfs (id)
);
